version: 0.1.{build}

image: Visual Studio 2017

matrix:
  fast_finish: true

install:
  - cmd: dotnet restore
    
configuration: Release

build:
  parallel: true
  project: chargen-nancy.sln
  verbosity: minimal
  
test_script:
  - cmd: dotnet test chargen-nancy-tests -c Release -v q --no-build
  - cmd: dotnet run -p chargen-nancy-storyteller -- run --tracing appveyor

deploy: off

artifacts:
  - path: stresults.htm
    name: StorytellerResults.htm